#pragma once

#define PRODUCT_NAME "MosChat"

#ifndef PRODUCT_VERSION_MAJOR
#define PRODUCT_VERSION_MAJOR   1
#define PRODUCT_VERSION_MINOR   0
#define PRODUCT_VERSION_PATCH   99
#endif

#define CrashID_Debug 99
#define CrashID_UnKnow_Quit 98
#define CrashID_Render_GPU 97
#define CrashID_Render_Render 96
#define CrashID_Render_Other 95


//测试：1207472126
#define PRODUCT_APPID           1494645593

#define PRODUCT_VERSION_INFO(a, b, c) a##,##b##,##c

#define PRODUCT_STR(x) #x
#define PRODUCT_STR2(x) PRODUCT_STR(x)
#define PRODUCT_VERSION_STR(a, b, c) PRODUCT_STR(a) "." PRODUCT_STR(b) "." PRODUCT_STR(c)

#define PRODUCT_FILE_VERSION PRODUCT_VERSION_INFO(PRODUCT_VERSION_MAJOR, PRODUCT_VERSION_MINOR, PRODUCT_VERSION_PATCH)
#define PRODUCT_VERSION PRODUCT_VERSION_INFO(PRODUCT_VERSION_MAJOR, PRODUCT_VERSION_MINOR, PRODUCT_VERSION_PATCH)

#define PRODUCT_FILE_VERSION_STRING PRODUCT_VERSION_STR(PRODUCT_VERSION_MAJOR, PRODUCT_VERSION_MINOR, PRODUCT_VERSION_PATCH)
#define PRODUCT_VERSION_STRING PRODUCT_VERSION_STR(PRODUCT_VERSION_MAJOR, PRODUCT_VERSION_MINOR, PRODUCT_VERSION_PATCH)

#define PRODUCT_ORIGINALFILENAME_STRING PRODUCT_STR2(PRODUCT_ORIGINALFILENAME)

#define _VER_STR_W(x) L#x
#define VER_STR_W(x) _VER_STR_W(x)
#define PRODUCT_VERSION_STR_W(a, b, c) VER_STR_W(a) L"." VER_STR_W(b) L"." VER_STR_W(c)
#define PRODUCT_VERSION_STRING_W PRODUCT_VERSION_STR_W(PRODUCT_VERSION_MAJOR, PRODUCT_VERSION_MINOR, PRODUCT_VERSION_PATCH)
