{
  "Local Clicker": "Local Clicker",
  "{1} Installer": "{1} Installer",
  "The best auto clicker ever": "The best auto clicker ever",
  "Copying files...": "Copying files...",
  "Creating desktop shortcut...": "Creating desktop shortcut...",
  "Install complete. Starting app...": "Install complete. Starting app...",
  "tips": "Tips",
  "OK": "OK",
  "Local Clicker": "Local Clicker",
  "The best auto clicker ever": "The best auto clicker ever",
  "Click Interval": "Click Interval: ",
  "mins": "mins",
  "secs": "secs",
  "milliseconds": "milliseconds",
  "Mouse Button": "Mouse Button: ",
  "Left Button": "Left",
  "Middle Button": "Middle",
  "Right Button": "Right",
  "Side Button": "Side",
  "Click Type": "ClickType: ",
  "One Click": "Single Click",
  "Double Click": "Double Click",
  "Click Repeat": "Click Repeat: ",
  "Repeat until stopped": "Repeat until stopped",
  "Repeat": "Repeat",
  "times": "times",
  "Global Hotkey": "Global Hotkey: ",
  "Press <span style=\'{1}\'>{2}</span> key to start/stop {3} {4}": "Press <span style=\'{1}\'>{2}</span>key to start/stop {4}",
  "Single Click": "Single Click",
  "search_url{1}": "https://www.google.com/search?q={1}",
  "Exit {1}": "Exit {1}",
  "Update file validation failed!": "Update file validation failed!",
  "Uninstall": "Uninstall",
  "{1} Uninstaller": "{1} Uninstaller",
}